import { Component, OnInit } from '@angular/core';
import { PlaylistDataService } from './service/data/playlist-data.service';
import { Playlist } from './playlist/playlist.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'djweb';
  mostRecentPlaylist: Playlist = new Playlist();
  autoDjPlaylist: Playlist = new Playlist();

  constructor(
    private playlistDataService: PlaylistDataService
    ){}

  ngOnInit(): void {
    /* AMS - The JSON response for Playlist includes some other stuff auto-generated by JPA/HAL, 
    so a tiny bit of manual assignment is needed. */
    this.playlistDataService.retrieveMostRecentPlaylist().subscribe(data => {
      console.log("Getting most recent playlist");
      //this.mostRecentPlaylist = new Playlist(data.id);
      this.mostRecentPlaylist.name = data.name;
      this.mostRecentPlaylist.playlistTracks = data._embedded.playlistTracks;
    });
    
    this.playlistDataService.retrievePlaylist(1).subscribe(data => {
      //this.autoDjPlaylist = new Playlist(1);
      this.autoDjPlaylist.name = data.name;
      this.autoDjPlaylist.playlistTracks = data._embedded.playlistTracks;
    });
  }
}
