import { Component, Input, OnInit } from '@angular/core';
import { PlaylistDataService } from '../service/data/playlist-data.service';
import { Track } from '../track/track.component';
import { ActivatedRoute, Router } from '@angular/router';
import { PlaylistTrack } from '../playlist-track/playlist-track.component';


export class Playlist {
  name!: string;
  dateModified!: Date;
  playlistTracks!: PlaylistTrack[];
  constructor(
    //public id: number
  ) {}
}

@Component({
  selector: 'app-playlist',
  templateUrl: './playlist.component.html',
  styleUrls: ['./playlist.component.scss']
})
export class PlaylistComponent implements OnInit {
  //@Input() id: number = 0;
  //playlist!: Playlist;
  @Input() playlist!: Playlist;

  constructor(
    private playlistDataService: PlaylistDataService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    //this.playlist = new Playlist(this.id);
    /* AMS - The JSON response includes some other stuff auto-generated by JPA/HAL, 
        so a tiny bit of manual assignment is needed. */
      /*
    this.playlistDataService.retrievePlaylist(this.id).subscribe(data => {
      this.playlist.id = data.id;
      this.playlist.name = data.name;
      this.playlist.playlistTracks = data._embedded.playlistTracks;
    });
    */
  }
}
